name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          cd functions
          pip install -r requirements.txt

      - name: Build web UI (if needed)
        run: echo "No build step for plain HTML/JS"

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FYL_GJA }}
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FYL_GJA }}' > ${HOME}/gcloud.json
          firebase deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FYL_GJA }}" --project fyl-gja --non-interactive --only hosting,functions